### ISSUE TITLE
TA2 requests

### ISSUE THREAD

**Issue by arunthomas** [cadets/ta1-integration-cadets#1]
Tracking issue for all TA2 requests. Many have been fixed or are no longer applicable.

MARPLE:

- [ ] Sometimes, the IP address of a netflow object is not in the definition of the
object. Instead, it is available in EVENT_Socket or other events.
- [ ]  Sometimes, there is no IP address for a netflow object, either in the
definition or in other related events.
- [ ]  ~Some versions of file objects have empty URL while other versions have a URL.~
- [ ]  ~Missing URL in some file objects even with considering all its versions.~ @alsz says: *this is expected behavior*
- [x]  Many file paths are in different fields like ["properties"]["fdpath”] or
["properties"]["upath1”] while they are expected to be in URL field of file objects.
- [x] Multiple definitions of same object.
- [ ] ~Some events are expected to be connected to netflow or file objects (like
recvmsg), but there is not such a SimpleEdge.~
- [ ]  ~The name of processes should be part of their definitions but usually it can
be found in the exec field of other events generated by that process. Even
the "exec" field does not provide a reliable way of mapping process names to
UUIDs if used with the "subjprocuuid" field. We encountered the same
"subjprocuuid" appearing with multiple "exec" process names.~ @alsz says: *this is expected behavior*
- [x]  I noticed this problem in the buildinject data, but did not look closely
enough through the engagement data to see if it is still present: A single
file was sometimes referenced as /usr/home/bob/crt1.o, /home/bob/crt1.o,
and something like /home/bob/./crt1.o. They all had different UUIDs as well.
- [x] the use of various attributes (instead of URL) for file names
- [ ] the fact that file names are not in any canonical form
- [ ] missing or inconsistent information about executables, and/or their command lines.

ADAPT:

- [ ] ~edges for all of the process parents and children~
- [ ] data was not where they expected. Would like attributes on processes
- [ ] sendto event - not connected to anything, not connected to writes,
  but not in some cases
- [ ] ~versioning semantics could be more useful~
- [x] Would like to represent multiple instances of file as single node in
  the graph
- [ ] timestamps on events, instead of nodes
- [ ] would like more attributed on each of the nodes
- [ ] would like better mapping of IPCs. Maybe files happen on TA2
  side. (e.g., exit codes, command lines)

RIPE:

TBD

**Comment by amstrnad** [comment]
I think the majority of the remaining requests are probably done, but we should look more closely. I've removed a few items and given them their own issues
