### ISSUE TITLE
Pass more attributes to CDM

### ISSUE THREAD

**Issue by arunthomas** [cadets/ta1-integration-cadets#4]
Encode more attributes as CDM properties. Consider the following:

* fd
* fdpath
* upath*
* miouuid
* retval

There are probably others that are worthwhile passing through to CDM.

**Comment by amstrnad** [comment]
I am now passing along all those listed except upath (but that should be included in the event itself)

**Comment by amstrnad** [comment]
- [x] ppid
- [x] RET_METAIO
- [x] ARG_METAIO
- [x] All the other file descriptors
